func_name = ['join', 'feof', 'pclose', 'chr', 'ord', 'htmlentities', 'void', 'defined', 'define', 'ftp_exec',
                 'apache_setenv', 'file_put_contents', 'parsekit_compile_file', 'session_set_save_handler',
                 'sqlite_open',
                 'ldap_search', 'fwrite', 'posix_mknod', 'eio_chmod', 'usleep', 'eio_fchown', 'dbx_query',
                 'runkit_method_copy', 'ftp_delete', 'imap_mail', 'imagecreatefromjpg', 'eio_unlink',
                 'strrev', 'runkit_function_redefine', 'ldap_read', 'imap_open', 'print', 'eio_close', 'fbsql_query',
                 'socket_write', 'Manipulation;', 'array_uintersect_uassoc', 'runkit_function_rename',
                 'pg_query', 'eio_mkdir', 'db2_execute', 'chgrp', 'sqlite_query', 'fgetc', 'preg_replace',
                 'get_meta_tags', 'iterator_apply', 'dba_popen', 'runkit_method_rename', 'array_filter',
                 'mysql_unbuffered_query',
                 'ibase_query', 'get_headers', 'fbsql_db_query', 'rename', 'runkit_function_copy', 'xdiff_file_rabdiff',
                 'sleep', 'ldap_connect', 'db2_exec', 'xptr_eval', 'expect_popen', 'ftp_nb_get',
                 'sqlite_create_aggregate', 'fread', 'readlink', 'curl_setopt', 'bzflush', 'singleQuery', 'unserialize',
                 'fflush', 'msession_connect', 'dio_write', 'mysqli_master_query', 'eio_readdir',
                 'imagecreatefromgif', 'eio_fdatasync', 'xdiff_file_diff', 'usort', 'pg_send_prepare', 'passthru',
                 'sybase_unbuffered_query', 'php_check_syntax', 'eio_dup2', 'proc_open', 'forward_static_call',
                 'array_udiff', 'imagecreatefromgd2part', 'yaml_parse', 'array_udiff_uassoc', 'eval', 'preg_filter',
                 'ftp_put', 'xdiff_file_patch', 'parse_str', 'session_id', 'fputcsv', 'imagecreatefromgd2',
                 'dio_read', 'arrayQuery', 'uasort', 'ldap_add', 'event_set', 'pfsockopen', 'mb_ereg_replace', 'gzfile',
                 'ingres_unbuffered_query', 'mysql_db_query', 'gzgetc', 'finfo_file', 'spl_autoload',
                 'unlink', 'ftruncate', 'runkit_constant_redefine', 'trigger_error', 'eio_fchmod',
                 'register_shutdown_function', 'ovrimos_exec', 'sqlite_single_query', 'spl_autoload_register',
                 'fdf_open',
                 'user_error', 'mysql_query', 'copy', 'putenv', 'dba_delete', 'bzwrite', 'rmdir', 'mysqli_query',
                 'w32api_invoke_function', 'printer_open', 'ereg', 'popen', 'gzuncompress', 'register_tick_function',
                 'base64_encode', 'Injection;', 'glob', 'ldap_list', 'ingres_execute', 'file_get_contents',
                 'call_user_func', 'bzread', 'yaml_parse_url', 'ovrimos_result_all', 'ifx_htmltbl_result', 'dba_fetch',
                 'array_walk', 'mysqli_stmt_execute', 'odbc_execute', 'setcookie', 'die', 'printf',
                 'w32api_register_function', 'ociexecute', 'chmod', 'ibase_execute', 'ftok', 'eio_busy', 'eio_mknod',
                 'xdiff_file_patch_binary',
                 'mb_send_mail', 'pg_prepare', 'uksort', 'ob_start', 'eio_fallocate', 'include_once', 'Disclosure;',
                 'ftp_fget', 'array_intersect_uassoc', 'gzgets', 'Splitting;', 'stream_resolve_include_path',
                 'preg_match', 'backticks',
                 'curl_setopt_array', 'ifx_do', 'xpath_eval_expression', 'eio_fstatvfs', 'dl', 'ini_restore',
                 'mssql_query', 'virtual', 'xpath_eval', 'stream_get_contents', 'ftp_nlist', 'eio_custom', 'exec',
                 'ini_set', 'dba_open',
                 'eio_rmdir', 'highlight_file', 'fprintf', 'fscanf', 'require_once', 'array_diff_uassoc',
                 'set_include_path', 'opendir', 'yaml_parse_file', 'system', 'runkit_function_add', 'assert',
                 'fsockopen', 'dba_insert',
                 'sqlite_unbuffered_query', 'is_a', 'parse_ini_file', 'recode_file', 'mail', 'ldap_delete', 'odbc_do',
                 'event_buffer_write', 'forward_static_call_array', 'oci_execute', 'define', 'yaml_emit_file',
                 'preg_replace_callback',
                 'gzpassthru', 'array_diff_ukey', 'sybase_query', 'base64_decode', 'stream_wrapper_register',
                 'vfprintf', 'xdiff_file_diff_binary', 'stream_get_line', 'fpassthru', 'array_walk_recursive', 'gzread',
                 'require', 'touch',
                 'print_r', 'mkdir', 'eregi', 'call_user_func_array', 'scandir', 'error_log', 'array_uintersect_assoc',
                 'event_buffer_new', 'fgetcsv', 'imagecreatefrompng', 'readgzfile', 'vprintf', 'msql_query', 'include',
                 'ovrimos_execute', 'sqlite_exec', 'runkit_method_redefine', 'pg_send_query_params', 'eio_chown',
                 'fgetss', 'ifx_query', 'invoke', 'sqlite_array_query', 'mb_parse_str', 'odbc_exec', 'ora_do',
                 'mb_eregi_replace',
                 'xdiff_file_bpatch', 'mssql_execute', 'stream_socket_client', 'setrawcookie', 'show_source',
                 'readfile', 'xdiff_file_bdiff', 'dotnet_load', 'move_uploaded_file', 'gzgetss', 'array_uintersect',
                 'ingres_query',
                 'ftp_nb_put', 'chown', 'gzputs', 'eio_write', 'imagecreatefromgd', 'php_strip_whitespace',
                 'ftp_nb_fget', 'mysqli_real_query', 'Execution;', 'create_function', 'shell_exec', 'set_error_handler',
                 'runkit_import', 'extract', 'exit', 'msql_db_query', 'fgets', 'registerPHPFunctions',
                 'xdiff_file_merge3', 'socket_connect', 'msql', 'header', 'shmop_write', 'odbc_result_all', 'loadXML',
                 '__invoke', 'fputs',
                 'assert_options', 'pcntl_exec', 'array_udiff_assoc', 'array_intersect_ukey', 'cyrus_query',
                 'runkit_method_add', 'session_register', 'stream_socket_server', 'array_reduce', 'ftp_get',
                 'array_map', 'pg_send_query',
                 'set_exception_handler', 'Reflection', 'ftp_chmod', 'eio_fstat', 'simplexml_load_file',
                 'sqlite_create_function', 'gzwrite', 'transformToXML', 'ora_exec', 'socket_send', 'zip_open',
                 'sqlite_popen', 'socket_bind']

stop_seq = [('UNARY_OP(!)', 'CALL', 'ZVAL', 'defined', 'ARG_LIST', 'ZVAL', 'shorttext'),
                ('AND(&&)', 'UNARY_OP(!)', 'CALL', 'ZVAL', 'defined', 'ARG_LIST', 'ZVAL', 'shorttext', 'EXIT'),
                ('AND(&&)', 'UNARY_OP(!)', 'CALL', 'ZVAL', 'defined', 'ARG_LIST', 'ZVAL', 'shorttext', 'EXIT', 'ZVAL',
                 'shorttext'),
                ('BINARY_OP(<)', 'BINARY_OP_ADD', 'CALL', 'ZVAL', 'shorttext', 'ARG_LIST', 'MAGIC_CONST(__FILE__)',
                 'ZVAL', 'number', 'CALL', 'ZVAL', 'shorttext', 'ARG_LIST'),
                ('OR(||)', 'CALL', 'ZVAL', 'defined', 'ARG_LIST', 'ZVAL', 'shorttext', 'EXIT'),
                ('OR(||)', 'CALL', 'ZVAL', 'defined', 'ARG_LIST', 'ZVAL', 'shorttext', 'EXIT', 'ZVAL', 'shorttext')]

stop_bak = {'special', 'PROP_ELEM', 'EXPR_LIST', 'FOR', 'ASSIGN_OP(+=)', 'BINARY_OP_ADD', 'METHOD_CALL',
                'STATIC_CALL',
                'virtual', 'GLOBAL', 'ARRAY_ELEM', 'ASSIGN_EQUAL', 'ARRAY', 'number', 'var_var', 'url', 'VAR',
                'shorttext', 'ZVAL', 'RETURN', 'variable', 'EXIT', 'ECHO', 'DIM', 'CONST', 'ARG_LIST',
                'PROP', 'AND(&&)', 'OR(||)', 'PARAM_LIST', 'GREATER(>)', 'UNARY_OP(!)', 'NAMESPACE', 'USE',
                'USE_ELEM', 'BINARY_OP_DOT', 'NEW', 'CLASS_NAME', 'BINARY_OP(==)', 'EMPTY', 'FOREACH', 'PARAM',
                'BREAK', 'CONTINUE', 'ISSET', 'BINARY_OP(*)', 'BINARY_OP(-)', 'BINARY_OP(/)', 'ASSIGN_OP(.=)',
                'BINARY_OP(!=)', 'GREATER_EQUAL(>=)', 'BINARY_OP(<)', 'ENCAPS_LIST', 'e_model', 'BINARY_OP(!==)',
                'PRE_INC(++)', 'UNARY_MINUS(-)', 'BINARY_OP(%)', 'CONDITIONAL', 'PROP_DECL', 'PROP_GROUP',
                'PROP_ELEM', 'THROW', 'DECLARE', 'CONST_ELEM', 'CATCH', 'CONST_DECL', 'NAME_LIST', 'CLASS_CONST',
                'BINARY_OP(===)', 'INSTANCEOF', 'TYPE(array)', 'UNSET', 'USE_TRAIT', 'CAST(int)', 'CAST(string)',
                'USE_TRAIT', 'CAST(bool)', 'void', 'STATIC_PROP', 'COALESCE(??)', 'POST_INC(++)', 'ASSIGN_REF(=&)',
                'CAST(array)', 'MAGIC_CONST(__DIR__)', 'BINARY_OP(&)', 'CLONE', 'CAST(object)', 'BINARY_OP(<=)',
                'CAST(double)', 'CLOSURE', 'STMT_LIST', 'REF', 'YIELD', 'BINARY_OP(|)', 'MAGIC_CONST(__CLASS__)',
                'BINARY_OP(>>)', 'ASSIGN_OP(/=)', 'BINARY_OP(**)', 'print', 'POST_DEC(--)', 'VOID',
                'MAGIC_CONST(__LINE__)',
                'BINARY_OP(>>)', 'MAGIC_CONST(__METHOD__)', 'ASSIGN_COALESCE(??=)', 'MAGIC_CONST(__FILE__)',
                'ASSIGN_OP(-=)',
                'STATIC', 'UNARY_PLUS_ADD', '{closure}', 'BINARY_OP(xor)', 'CLOSURE_USES', 'print_r', 'ASSIGN_OP(%=)',
                'ASSIGN_OP(|=)', 'MAGIC_CONST(__NAMESPACE__)', 'YIELD_FROM', 'ASSIGN_OP(*=)', 'BINARY_OP(<=>)',
                'PRE_DEC(--)',
                'UNPACK(...)', 'IF_ELEM', 'IF', 'METHOD', 'CLASS', 'longtext', 'CATCH_LIST', 'TRY', 'TYPE(callable)',
                'sql_query',
                'BINARY_OP(<<)', 'ASSIGN_OP(>>=)', 'long_danger_info', 'UNARY_OP(~)', 'PARAM(&)',
                'ASSIGN_OP(^=)', 'ASSIGN_OP(&=)', 'ARROW_FUNC', 'MAGIC_CONST(__FUNCTION__)', 'BINARY_OP(^)',
                'info', 'SWITCH', 'SWITCH_LIST', 'SWITCH_CASE', 'WHILE', 'define', 'copy', 'Copy', 'session_id'}