
stop_seq = [('UNARY_OP(!)', 'CALL', 'ZVAL', 'defined', 'ARG_LIST', 'ZVAL', 'shorttext'),
                ('AND(&&)', 'UNARY_OP(!)', 'CALL', 'ZVAL', 'defined', 'ARG_LIST', 'ZVAL', 'shorttext', 'EXIT'),
                ('AND(&&)', 'UNARY_OP(!)', 'CALL', 'ZVAL', 'defined', 'ARG_LIST', 'ZVAL', 'shorttext', 'EXIT', 'ZVAL',
                 'shorttext'),
                ('BINARY_OP(<)', 'BINARY_OP_ADD', 'CALL', 'ZVAL', 'shorttext', 'ARG_LIST', 'MAGIC_CONST(__FILE__)',
                 'ZVAL', 'number', 'CALL', 'ZVAL', 'shorttext', 'ARG_LIST'),
                ('OR(||)', 'CALL', 'ZVAL', 'defined', 'ARG_LIST', 'ZVAL', 'shorttext', 'EXIT'),
                ('OR(||)', 'CALL', 'ZVAL', 'defined', 'ARG_LIST', 'ZVAL', 'shorttext', 'EXIT', 'ZVAL', 'shorttext')]

stop_bak = {'special', 'PROP_ELEM', 'EXPR_LIST', 'FOR', 'ASSIGN_OP(+=)', 'BINARY_OP_ADD', 'METHOD_CALL',
                'STATIC_CALL',
                'virtual', 'GLOBAL', 'ARRAY_ELEM', 'ASSIGN_EQUAL', 'ARRAY', 'number', 'var_var', 'url', 'VAR',
                'shorttext', 'ZVAL', 'RETURN', 'variable', 'EXIT', 'ECHO', 'DIM', 'CONST', 'ARG_LIST',
                'PROP', 'AND(&&)', 'OR(||)', 'PARAM_LIST', 'GREATER(>)', 'UNARY_OP(!)', 'NAMESPACE', 'USE',
                'USE_ELEM', 'BINARY_OP_DOT', 'NEW', 'CLASS_NAME', 'BINARY_OP(==)', 'EMPTY', 'FOREACH', 'PARAM',
                'BREAK', 'CONTINUE', 'ISSET', 'BINARY_OP(*)', 'BINARY_OP(-)', 'BINARY_OP(/)', 'ASSIGN_OP(.=)',
                'BINARY_OP(!=)', 'GREATER_EQUAL(>=)', 'BINARY_OP(<)', 'ENCAPS_LIST', 'e_model', 'BINARY_OP(!==)',
                'PRE_INC(++)', 'UNARY_MINUS(-)', 'BINARY_OP(%)', 'CONDITIONAL', 'PROP_DECL', 'PROP_GROUP',
                'PROP_ELEM', 'THROW', 'DECLARE', 'CONST_ELEM', 'CATCH', 'CONST_DECL', 'NAME_LIST', 'CLASS_CONST',
                'BINARY_OP(===)', 'INSTANCEOF', 'TYPE(array)', 'UNSET', 'USE_TRAIT', 'CAST(int)', 'CAST(string)',
                'USE_TRAIT', 'CAST(bool)', 'void', 'STATIC_PROP', 'COALESCE(??)', 'POST_INC(++)', 'ASSIGN_REF(=&)',
                'CAST(array)', 'MAGIC_CONST(__DIR__)', 'BINARY_OP(&)', 'CLONE', 'CAST(object)', 'BINARY_OP(<=)',
                'CAST(double)', 'CLOSURE', 'STMT_LIST', 'REF', 'YIELD', 'BINARY_OP(|)', 'MAGIC_CONST(__CLASS__)',
                'BINARY_OP(>>)', 'ASSIGN_OP(/=)', 'BINARY_OP(**)', 'print', 'POST_DEC(--)', 'VOID',
                'MAGIC_CONST(__LINE__)',
                'BINARY_OP(>>)', 'MAGIC_CONST(__METHOD__)', 'ASSIGN_COALESCE(??=)', 'MAGIC_CONST(__FILE__)',
                'ASSIGN_OP(-=)',
                'STATIC', 'UNARY_PLUS_ADD', '{closure}', 'BINARY_OP(xor)', 'CLOSURE_USES', 'print_r', 'ASSIGN_OP(%=)',
                'ASSIGN_OP(|=)', 'MAGIC_CONST(__NAMESPACE__)', 'YIELD_FROM', 'ASSIGN_OP(*=)', 'BINARY_OP(<=>)',
                'PRE_DEC(--)',
                'UNPACK(...)', 'IF_ELEM', 'IF', 'METHOD', 'CLASS', 'longtext', 'CATCH_LIST', 'TRY', 'TYPE(callable)',
                'sql_query',
                'BINARY_OP(<<)', 'ASSIGN_OP(>>=)', 'long_danger_info', 'UNARY_OP(~)', 'PARAM(&)',
                'ASSIGN_OP(^=)', 'ASSIGN_OP(&=)', 'ARROW_FUNC', 'MAGIC_CONST(__FUNCTION__)', 'BINARY_OP(^)',
                'info', 'SWITCH', 'SWITCH_LIST', 'SWITCH_CASE', 'WHILE', 'define', 'copy', 'Copy', 'session_id'}